# Array Syntax

Goal:  Understand the difference between lists and arrays.


In [1]:
import numpy as np

a = np.array([4,8,20,16])
a = a/4
print(a)

[1. 2. 5. 4.]


In [12]:
b = [4,8,20,16]
b = b/4
print(b)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [13]:
for i in range(len(b)):
    print(b[i]/4)

1.0
2.0
5.0
4.0


In [14]:
x = np.arange(0,10,1)
y = x**2
print(x,y)


[0 1 2 3 4 5 6 7 8 9] [ 0  1  4  9 16 25 36 49 64 81]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [15]:
y = [] #generate an empty list
for i in range(len(x)):
    y.append(x[i]**2)
    
z = y**2




TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [17]:
y = [] #generate an empty list
for i in range(len(x)):
    y.append(x[i]**2)
y = np.asarray(y)
    
z = y**2
print(z)

[   0    1   16   81  256  625 1296 2401 4096 6561]


In [2]:
x = np.random.rand(100)

In [3]:
x

array([0.67912993, 0.33551912, 0.63409397, 0.81930199, 0.71608012,
       0.03578236, 0.39884796, 0.8015937 , 0.56281314, 0.14672038,
       0.59440815, 0.8091945 , 0.78950881, 0.27405162, 0.23925149,
       0.54027864, 0.84345572, 0.36909285, 0.61852591, 0.66298359,
       0.48092419, 0.60010833, 0.14889321, 0.81488259, 0.24338643,
       0.32861608, 0.76609771, 0.78208555, 0.23787327, 0.12137264,
       0.17261338, 0.429929  , 0.59199366, 0.30182264, 0.17727431,
       0.24742793, 0.15907239, 0.2477713 , 0.80200945, 0.65015134,
       0.03729711, 0.57966209, 0.59182997, 0.50804206, 0.42477284,
       0.38512997, 0.34600306, 0.4683844 , 0.80707247, 0.88373957,
       0.83891361, 0.25516931, 0.6915424 , 0.07653129, 0.79005896,
       0.17170961, 0.06229982, 0.05517913, 0.03278219, 0.22539444,
       0.39483494, 0.38586287, 0.06100564, 0.77856545, 0.89029741,
       0.94669558, 0.83338218, 0.05286947, 0.13058311, 0.11984206,
       0.55258379, 0.37626407, 0.24287864, 0.99570337, 0.72794

In [4]:
np.where(x>0.5, 0.5, x)

array([0.5       , 0.33551912, 0.5       , 0.5       , 0.5       ,
       0.03578236, 0.39884796, 0.5       , 0.5       , 0.14672038,
       0.5       , 0.5       , 0.5       , 0.27405162, 0.23925149,
       0.5       , 0.5       , 0.36909285, 0.5       , 0.5       ,
       0.48092419, 0.5       , 0.14889321, 0.5       , 0.24338643,
       0.32861608, 0.5       , 0.5       , 0.23787327, 0.12137264,
       0.17261338, 0.429929  , 0.5       , 0.30182264, 0.17727431,
       0.24742793, 0.15907239, 0.2477713 , 0.5       , 0.5       ,
       0.03729711, 0.5       , 0.5       , 0.5       , 0.42477284,
       0.38512997, 0.34600306, 0.4683844 , 0.5       , 0.5       ,
       0.5       , 0.25516931, 0.5       , 0.07653129, 0.5       ,
       0.17170961, 0.06229982, 0.05517913, 0.03278219, 0.22539444,
       0.39483494, 0.38586287, 0.06100564, 0.5       , 0.5       ,
       0.5       , 0.5       , 0.05286947, 0.13058311, 0.11984206,
       0.5       , 0.37626407, 0.24287864, 0.5       , 0.5    

In [5]:
x[x>0.5]

array([0.67912993, 0.63409397, 0.81930199, 0.71608012, 0.8015937 ,
       0.56281314, 0.59440815, 0.8091945 , 0.78950881, 0.54027864,
       0.84345572, 0.61852591, 0.66298359, 0.60010833, 0.81488259,
       0.76609771, 0.78208555, 0.59199366, 0.80200945, 0.65015134,
       0.57966209, 0.59182997, 0.50804206, 0.80707247, 0.88373957,
       0.83891361, 0.6915424 , 0.79005896, 0.77856545, 0.89029741,
       0.94669558, 0.83338218, 0.55258379, 0.99570337, 0.72794433,
       0.6366616 , 0.73514148, 0.53359315, 0.70250108, 0.90807747,
       0.5205516 , 0.75541706, 0.58362034, 0.85070697, 0.79872253])

In [9]:
np.logical_and(x>0.5, x<0.75)

array([ True, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False, False,  True, False, False,
        True,  True, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False,  True,  True,  True, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False,  True,  True,  True, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False])

In [10]:
def find_closest(arr, val):
    return np.argmin(np.abs(arr-val))


In [12]:
find_closest(x, 0.7)

87

In [13]:
x[87]

0.7025010767356044

In [17]:
x[:] = np.where(x>0.6, 0.7, 0.1)

In [19]:
x[:] = np.array([1,2,3])

ValueError: could not broadcast input array from shape (3) into shape (100)

In [20]:
x = np.random.rand(100)
y = np.random.rand(100)

In [22]:
np.multiply(x,y, out=x)

array([0.2632094 , 0.02764988, 0.24814066, 0.27378395, 0.12955193,
       0.16293452, 0.05459373, 0.18009227, 0.00549799, 0.11084851,
       0.01471291, 0.01992766, 0.24389658, 0.00380751, 0.36571637,
       0.20355394, 0.05787167, 0.11414523, 0.33212405, 0.00910292,
       0.09639325, 0.12603422, 0.21974415, 0.4594747 , 0.00537612,
       0.16486814, 0.33079716, 0.53420096, 0.06429088, 0.03522411,
       0.70683212, 0.63699618, 0.37834931, 0.42978669, 0.54490106,
       0.50839152, 0.60342602, 0.72171406, 0.15346108, 0.58228121,
       0.05131558, 0.05816925, 0.18069909, 0.31255437, 0.14528334,
       0.26217749, 0.00108671, 0.41829045, 0.34013071, 0.08504418,
       0.19218239, 0.72752223, 0.35442016, 0.14637891, 0.31209762,
       0.35649306, 0.09634286, 0.64554953, 0.09100667, 0.09785422,
       0.40534523, 0.00436848, 0.13166023, 0.40737427, 0.15028015,
       0.12271959, 0.0196978 , 0.0280872 , 0.03295666, 0.20269886,
       0.1483076 , 0.0343848 , 0.05546871, 0.08763434, 0.27658