# Solution of simultaneous linear equations
- Solution tedious, involving many operations and prone to human error.
- Large systems of equations are perfect for computers!
- Example: consider the following system of equations

\begin{align*}
2w + x + 4y + z &= -4 \\
3w + 4x - y - z &= 3 \\
w - 4x + y + 5z &= 9 \\
2w - 2x + y + 3z &= 7
\end{align*}

- Write as a matrix equation for the simplest way to think abou the system of equations.

\begin{align*}
\begin{pmatrix}
2 & 1 & 4 & 1 \\
3 & 4 & -1 & -1 \\
1 & -4 & 1 & 5 \\
2 & -2 & 1 & 3 \\
\end{pmatrix}
\begin{pmatrix}
w \\
x \\
y \\
z \\
\end{pmatrix}
=
\begin{pmatrix}
-4 \\
3 \\
9 \\
7 \\
\end{pmatrix}
\end{align*}

- In shorthand, we can write 

$$\mathbf{Ax} = \mathbf{v}$$

- Possible to solve by finding the inverse matrix, i.e., 

\begin{align*}
\mathbf{A}^{-1}\mathbf{Ax} &= \mathbf{A}^{-1}\mathbf{v} \\
\mathbf{x} &= \mathbf{A}^{-1}\mathbf{v}
\end{align*}

- Always possible to "try" finding the inverse. But this is not always possible. Let's try.

In [2]:
import numpy as np
from scipy import linalg
A = np.array([[1., 2.], [3., 4.]])
print(A)
Ainv = linalg.inv(A)
print(np.dot(A, Ainv))

A = np.array([[2., 1., 4., 1.], [3., 4., -1., -1.], [1., -4., 1., 5.], [2., -2., 1., 3]])
v = np.array([-4., 3., 9., 7.])
print(A)
print(v)
Ainv = linalg.inv(A)
print(np.dot(A, Ainv))

x = np.matmul(Ainv, v)
print(x)
x = np.matmul(Ainv, v.transpose())
print(x)

[[1. 2.]
 [3. 4.]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[-4.  3.  9.  7.]
[[ 1.00000000e+00  0.00000000e+00  1.11022302e-16  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00  2.22044605e-16 -2.22044605e-16]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00  2.22044605e-16]
 [-2.77555756e-17 -2.22044605e-16 -6.66133815e-16  1.00000000e+00]]
[ 2. -1. -2.  1.]
[ 2. -1. -2.  1.]


(JK note: The inverse matrix of $\mathbf{A}$ actually doesn't match result from the pdf version in the combined lecture notes... I'm not sure if it's because of an updated library or what. (I copied and pasted the code, so there technically shouldn't be any problem in that sense))

# Gaussian elimination
- Another alternative to determining the inverse matrix. Sometimes Gaussian elimination is faster, simpler, and more accurate than finding the inverse matrix.
- Based on the "rules" of linear algebra: 1) multiply any of the equations by a constant, 2) take a linear combination of two equations to get another correct equation.
- First eliminate the lower off-diagonal terms.
    1. Make the top-left most element of the matrix = 1 by dividing by its value.
    2. Eliminate the lower off-diagonal elements from the first column with the "rules" of linear algebra.
    3. Repeat steps 1 and 2, but for the second row and column.

\begin{align*}
\begin{pmatrix}
1   &   0.5 &   2   &   0.5 \\
0   &   1   &   -2.8 &  -1  \\
0   &   0   &   1   &   0   \\
0   &   0   &   0   &   1   \\
\end{pmatrix}
\begin{pmatrix}
w \\
x \\
y \\
z \\
\end{pmatrix}
=
\begin{pmatrix}
-2 \\
3.6 \\
-2 \\
1 \\
\end{pmatrix}
\end{align*}

- Second, backsubstitute starting with the lower right corner of the matrix to solve (which already has the solution from the diagonal element).

\begin{align*}
z &= 1 \\
y &= -2 \\
x &= -1 \\
w &= 2
\end{align*}

In [3]:
# From Mark Newman, Computational Physics
A = np.array([[ 2, 1, 4, 1 ],
              [ 3, 4, -1, -1 ],
              [ 1, -4, 1, 5 ],
              [ 2, -2, 1, 3 ]],float)
v = np.array([ -4, 3, 9, 7 ],float)
N = len(v)

# Gaussian elimination
for m in range(N):

    # Divide by the diagonal element
    div = A[m,m]
    A[m,:] /= div
    v[m] /= div

    print(A)
    
    # Now subtract from the lower rows
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]

# Backsubstitution
x = np.empty(N,float)
for m in range(N-1,-1,-1):
    x[m] = v[m]
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]
print(x)

[[ 1.   0.5  2.   0.5]
 [ 3.   4.  -1.  -1. ]
 [ 1.  -4.   1.   5. ]
 [ 2.  -2.   1.   3. ]]
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [ 0.  -4.5 -1.   4.5]
 [ 0.  -3.  -3.   2. ]]
[[  1.    0.5   2.    0.5]
 [  0.    1.   -2.8  -1. ]
 [ -0.   -0.    1.   -0. ]
 [  0.    0.  -11.4  -1. ]]
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]
[ 2. -1. -2.  1.]
