# Numpy!

In [1]:
import numpy as np

## Array Creation

In [2]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.array([np.zeros(3),np.zeros(3)])


array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.array([np.ones(2),np.ones(2),np.ones(2)])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.random.randint(0,10,size=(3,2))

array([[2, 2],
       [7, 1],
       [6, 8]])

In [9]:
np.random.rand(100,2)

array([[0.21418169, 0.6554902 ],
       [0.85683092, 0.1269871 ],
       [0.45063142, 0.20734076],
       [0.23645115, 0.86037471],
       [0.00646432, 0.60968492],
       [0.5420278 , 0.02586685],
       [0.16126587, 0.17015541],
       [0.71449108, 0.38099701],
       [0.82147368, 0.6319175 ],
       [0.34519911, 0.85778647],
       [0.71400994, 0.17981601],
       [0.71256849, 0.24178815],
       [0.42180971, 0.99051652],
       [0.75570104, 0.76031371],
       [0.4159635 , 0.58399559],
       [0.221002  , 0.44828201],
       [0.39348776, 0.42522885],
       [0.55172257, 0.21455174],
       [0.72398025, 0.62490517],
       [0.54428346, 0.02107111],
       [0.43133076, 0.36233531],
       [0.91873586, 0.66017991],
       [0.51323885, 0.81303934],
       [0.01417541, 0.83928499],
       [0.1103697 , 0.45014486],
       [0.42609715, 0.82582818],
       [0.47100234, 0.50541917],
       [0.74501261, 0.17960364],
       [0.08597142, 0.52902668],
       [0.45809149, 0.95830112],
       [0.

In [10]:
np.random.randint(1,24,size=(2,3,4))

array([[[ 8, 16, 17, 18],
        [ 6, 23, 23, 23],
        [16, 15, 17, 11]],

       [[ 8, 21, 15,  2],
        [14, 14,  3, 17],
        [ 5, 21, 12,  2]]])

## Array Indexing
Task: Let X be a numpy array, and `X = np.array([1,2,3,4,5])`

In [11]:
X = np.array([1,2,3,4,5])

In [12]:
X[0]

1

In [13]:
X[-1]

5

In [14]:
X[:3]

array([1, 2, 3])

In [15]:
X[-3:]

array([3, 4, 5])

In [16]:
X[1::2]

array([2, 4])

Task: Let X be a numpy matrix with dimensions 3*4, and filled from 0 to 11.

In [17]:
X = np.arange(0,12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
X[0]

array([0, 1, 2, 3])

In [19]:
X[:,0]

array([0, 4, 8])

In [20]:
X[0,0]

0

In [21]:
X[-1]

array([ 8,  9, 10, 11])

In [22]:
X[:,-1]

array([ 3,  7, 11])

In [23]:
X[-1,-1]

11

In [24]:
X[:-1]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
X[:,:-1]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [26]:
X[:2,:2]

array([[0, 1],
       [4, 5]])

In [27]:
X = np.arange(12)

Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [28]:
# Because I could see the same pattern for different structures, I just decided to create a function (so I don't have to copy/paste and edit so many small things)
def print_info(a):
  print(np.sum(a),np.mean(a),np.median(a),np.std(a),np.var(a),np.max(a),np.min(a))

In [29]:
print_info(X)

66 5.5 5.5 3.452052529534663 11.916666666666666 11 0


Task: Create a numpy matrix as n*m, print the sum, mean, std, var, max, min of the 1st row of it.

In [30]:
X = X.reshape(3,4)

In [31]:
print_info(X[0])   # info for first row of matrix X

6 1.5 1.5 1.118033988749895 1.25 3 0


Task: Create a numpy matrix... print the sum, mean, std,... of the 1st column of it.

In [32]:
print_info(X[:,0]) # info for first column of matrix X

12 4.0 4.0 3.265986323710904 10.666666666666666 8 0


## Array Linear Algebra

Task: Create two numpy matrix X with 2 \* 2, and Y with 2 \* 2. 

Practice Linear Algebra operations such as $+,-,*,$ `.T`,`@`, etc.

In [33]:
X = np.arange(4).reshape(2,2)
Y = np.arange(4,8).reshape(2,2)
print(X)
print(Y)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [34]:
print(f'{X+Y}\n{X-Y}\n{X*Y}\n{X.T}\n{X@Y}\n{X%Y}')

[[ 4  6]
 [ 8 10]]
[[-4 -4]
 [-4 -4]]
[[ 0  5]
 [12 21]]
[[0 2]
 [1 3]]
[[ 6  7]
 [26 31]]
[[0 1]
 [2 3]]


In [35]:
import pandas as pd


In [36]:
cols = ['Country', 'GDP', 'Population']
USA = pd.Series(['United States',25346805, 332943701], index = cols)
China = pd.Series(['China',19911593, 1425881285], index = cols)
Japan = pd.Series(['Japan',4912147, 125502000], index = cols)
Germany = pd.Series(['Germany',4256540, 83695430], index = cols)
India = pd.Series(['India',3534743, 1417945080], index = cols)
UK = pd.Series(['UK',3376003, 67081234], index = cols)
France = pd.Series(['France',2936702, 67874000], index = cols)
Canada = pd.Series(['Canada',2221218, 38856839], index = cols)
Italy = pd.Series(['Italy',2058330, 58906742], index = cols)
Brazil = pd.Series(['Brazil',1833274, 214956683], index = cols)

df = pd.DataFrame([USA, China, Japan, Germany, India, UK, France, Canada, Italy, Brazil])
df

Country       GDP  Population
0  United States  25346805   332943701
1          China  19911593  1425881285
2          Japan   4912147   125502000
3        Germany   4256540    83695430
4          India   3534743  1417945080
5             UK   3376003    67081234
6         France   2936702    67874000
7         Canada   2221218    38856839
8          Italy   2058330    58906742
9         Brazil   1833274   214956683

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Country     10 non-null     object
 1   GDP         10 non-null     int64 
 2   Population  10 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 368.0+ bytes


In [38]:
df[['Country','GDP']]

Country       GDP
0  United States  25346805
1          China  19911593
2          Japan   4912147
3        Germany   4256540
4          India   3534743
5             UK   3376003
6         France   2936702
7         Canada   2221218
8          Italy   2058330
9         Brazil   1833274

In [39]:
df[['Country','Population']]

Country  Population
0  United States   332943701
1          China  1425881285
2          Japan   125502000
3        Germany    83695430
4          India  1417945080
5             UK    67081234
6         France    67874000
7         Canada    38856839
8          Italy    58906742
9         Brazil   214956683

In [40]:
df.loc[0]

Country       United States
GDP                25346805
Population        332943701
Name: 0, dtype: object

In [41]:
df[df['GDP']>5000000]

Country       GDP  Population
0  United States  25346805   332943701
1          China  19911593  1425881285

In [42]:
df[df['GDP']>3000000]

Country       GDP  Population
0  United States  25346805   332943701
1          China  19911593  1425881285
2          Japan   4912147   125502000
3        Germany   4256540    83695430
4          India   3534743  1417945080
5             UK   3376003    67081234

In [43]:
df[df['Population']>1000000000]

Country       GDP  Population
1   China  19911593  1425881285
4   India   3534743  1417945080

In [44]:
df[df['Population']<300000000]

Country      GDP  Population
2    Japan  4912147   125502000
3  Germany  4256540    83695430
5       UK  3376003    67081234
6   France  2936702    67874000
7   Canada  2221218    38856839
8    Italy  2058330    58906742
9   Brazil  1833274   214956683

In [45]:
df[df['Population'].between(300000000, 500000000)]

Country       GDP  Population
0  United States  25346805   332943701

In [46]:
df['GDP per capita'] = df['GDP']/df['Population']
df

Country       GDP  Population  GDP per capita
0  United States  25346805   332943701        0.076129
1          China  19911593  1425881285        0.013964
2          Japan   4912147   125502000        0.039140
3        Germany   4256540    83695430        0.050857
4          India   3534743  1417945080        0.002493
5             UK   3376003    67081234        0.050327
6         France   2936702    67874000        0.043267
7         Canada   2221218    38856839        0.057164
8          Italy   2058330    58906742        0.034942
9         Brazil   1833274   214956683        0.008529

In [47]:
df.describe()

GDP    Population  GDP per capita
count  1.000000e+01  1.000000e+01       10.000000
mean   7.038736e+06  3.833643e+08        0.037681
std    8.371837e+06  5.545693e+08        0.023292
min    1.833274e+06  3.885684e+07        0.002493
25%    2.400089e+06  6.727943e+07        0.019209
50%    3.455373e+06  1.045987e+08        0.041203
75%    4.748245e+06  3.034469e+08        0.050725
max    2.534680e+07  1.425881e+09        0.076129

In [48]:
df[['GDP','Population','GDP per capita']].var()

GDP               7.008765e+13
Population        3.075471e+17
GDP per capita    5.425327e-04
dtype: float64

In [49]:
df[['GDP','Population','GDP per capita']].std()

GDP               8.371837e+06
Population        5.545693e+08
GDP per capita    2.329233e-02
dtype: float64

In [50]:
df.sum()

Country           United StatesChinaJapanGermanyIndiaUKFranceCan...
GDP                                                        70387355
Population                                               3833642994
GDP per capita                                             0.376813
dtype: object

JK notes: I think the outputs for variance and std are swapped in the assignment instructions (judging by the order of magnitude of each values). 