# Using Boolean Arrays

In [ ]:
import numpy as np

In [ ]:
np.random.seed(1)
ar = np.random.randint(100, size=10)
ar

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [ ]:
ar_isodd = ar % 2 == 1
ar_isodd

array([ True, False, False,  True,  True,  True,  True, False, False,
        True])

In [ ]:
ar[ar_isodd]

array([37,  9, 75,  5, 79,  1])

In [ ]:
ar[ar % 2 == 1]

array([37,  9, 75,  5, 79,  1])