In [ ]:
import numpy as np

## Efficiency

In [ ]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
np.arange(10) ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
%timeit -n 1000 [x**2 for x in range(1000)]
%timeit -n 1000 np.arange(1000) ** 2

228 µs ± 17.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
2.42 µs ± 815 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Creating a Simple Array

In [ ]:
ls = [1,2,3,4,5]
np.array(ls)

array([1, 2, 3, 4, 5])

### Getting Basic Information about an Array

In [ ]:
ar = np.array([1,2,3,4,5])
ar_type = type(ar)
array_size = np.size(ar)
array_dimensions = ar.ndim
array_data_type = ar.dtype

print('''Object type: {}
Array size: {},
Array dimensions: {},
Array data type: {}'''.format(ar_type,
                              array_size,
                              array_dimensions,
                              array_data_type))

Object type: <class 'numpy.ndarray'>
Array size: 5,
Array dimensions: 1,
Array data type: int64


### np.arange()

In [ ]:
ar1 = np.arange(10)
print('ar1:', ar1)

ar2 = np.arange(5,11)
print('ar2:', ar2)

ar3 = np.arange(0,13,3)
print('ar3:', ar3)

ar4 = np.arange(4,-4,-1)
print('ar4:', ar4)

ar1: [0 1 2 3 4 5 6 7 8 9]
ar2: [ 5  6  7  8  9 10]
ar3: [ 0  3  6  9 12]
ar4: [ 4  3  2  1  0 -1 -2 -3]


In [ ]:
ar5 = np.arange(1,5,1)
print(ar5, type(ar5[0]))

ar6 = np.arange(1,5,.5)
print(ar6, type(ar6[0]))

ar7 = np.arange(1,5, dtype=float)
print(ar7, type(ar7[0]))

[1 2 3 4] <class 'numpy.int64'>
[1.  1.5 2.  2.5 3.  3.5 4.  4.5] <class 'numpy.float64'>
[1. 2. 3. 4.] <class 'numpy.float64'>


In [ ]:
ar = np.arange(1,10)
print( type(ar[0]))

ar[5] = 1.5
print( ar[5] )

<class 'numpy.int64'>
1


## Similar to Lists
ndarrays are iterators

In [ ]:
ls = [x**2 for x in range(10)]
ar = np.arange(10) ** 2

for i in ls:
    print(i, end=' ')

print('\n', '-' * 25)

for i in ar:
    print(i, end=' ')

0 1 4 9 16 25 36 49 64 81 
 -------------------------
0 1 4 9 16 25 36 49 64 81 

## Different from Lists

### Operators that behave differently

In [ ]:
ls = [1,2,3,4,5]
print(ls)
print(ls + ls) #Appends list to itself
print(ls * 2) #Repeats list twice

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
ar = np.arange(1,6)
print(ar)
print(ar + ar) #Adds ar[0] to ar[0], ar[1] to ar[1], etc.
print(ar * 2) #Multiplies each element of array by 2

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [ ]:
ar1 = np.arange(1,6)
s = 2
ls = [2,2,2,2,2]
ar2 = np.array( [2,2,2,2,2] )

print(ar1 * s)
print(ar1 * ls)
print(ar1 * ar2)

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [ ]:
ar = np.arange(1,6)
print(ar + 2) #Add 2 to each element of array
print(ar - 2) #Subtract 2 from each element of array
print(ar / 2) #Divide each element of array by 2
print(ar ** 2) #Square each element of array
print(ar ** .5) #Get square root of each element of array
ar += 10 #Add 10 to each element of array
print(ar)

[3 4 5 6 7]
[-1  0  1  2  3]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[11 12 13 14 15]


## Universal Functions

### Zipping two iterables

In [ ]:
r1 = range(1,10)
r2 = range(10,1,-1)
z = zip(r1,r2)
z

### Displaying the zip as a list

In [ ]:
list(z)

[(1, 10), (2, 9), (3, 8), (4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (9, 2)]

### Looping through zip object to create list

In [ ]:
ls = []
for i1, i2 in zip(r1,r2):
    ls.append(i1 * i2)
ls

[10, 18, 24, 28, 30, 30, 28, 24, 18]

### Multiplying two ndarrays

In [ ]:
ar1 = np.arange(1,10)
ar2 = np.arange(10,1,-1)
np.multiply(ar1,ar2)

array([10, 18, 24, 28, 30, 30, 28, 24, 18])

### Adding array-like objects

In [ ]:
ls = [1,3,5,7]
r = range(0,4)
ls, r, np.add(ls,r)

([1, 3, 5, 7], range(0, 4), array([ 1,  4,  7, 10]))

### Some Examples of Universal Functions

In [ ]:
ar_ints = np.arange(1,6)
ar_floats = np.arange(1,7.5,1.5)

In [ ]:
np.add(ar_ints, ar_floats)

array([ 2. ,  4.5,  7. ,  9.5, 12. ])

In [ ]:
np.negative(ar_ints)

array([-1, -2, -3, -4, -5])

In [ ]:
np.square(ar_ints)

array([ 1,  4,  9, 16, 25])

In [ ]:
np.hypot(ar_ints, ar_ints)

array([1.41421356, 2.82842712, 4.24264069, 5.65685425, 7.07106781])

In [ ]:
np.greater(ar_ints, ar_floats)

array([False, False, False, False, False])

In [ ]:
np.ceil(ar_floats)

array([1., 3., 4., 6., 7.])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=dfff8ba7-aef1-4bba-91c9-7743c312b252' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>