# Using Boolean Arrays

In [ ]:
import numpy as np

In [ ]:
np.random.seed(1)
ar = np.random.randint(100, size=10)
ar

array([37, 12, 72,  9, 75,  5, 79, 64, 16,  1])

In [ ]:
ar_isodd = ar % 2 == 1
ar_isodd

array([ True, False, False,  True,  True,  True,  True, False, False,
        True])

In [ ]:
ar[ar_isodd]

array([37,  9, 75,  5, 79,  1])

In [ ]:
ar[ar % 2 == 1]

array([37,  9, 75,  5, 79,  1])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=dfff8ba7-aef1-4bba-91c9-7743c312b252' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>