# Multi-dimensional Arrays

In [ ]:
import numpy as np

In [ ]:
mda = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])

print('Num dimensions: ', mda.ndim)
print('Second row: ', mda[1])
print('Second column: ', mda[0:3, 1])
print('Second column: ', mda[:, 1]) #short hand
print('2nd element in 2nd row:', mda[1, 1])

Num dimensions:  2
Second row:  [4 5 6]
Second column:  [2 5 8]
Second column:  [2 5 8]
2nd element in 2nd row: 5


### Retrieve Row

In [ ]:
row2 = mda[1]
row2, type(row2), row2.ndim

(array([4, 5, 6]), numpy.ndarray, 1)

### Retrieve Cell within Row

In [ ]:
row3 = mda[2]
row3cell2 = row3[1]
row3cell2

8

In [ ]:
row3cell2 = mda[2,1]
row3cell2

8

### Retrieve All Rows

In [ ]:
all_rows = mda[0:len(mda)]
all_rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
all_rows = mda[:]
all_rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Retrieve One Column

In [ ]:
col2 = mda[:,1]
col2

array([2, 5, 8])

### Retrieve Last Two Columns

In [ ]:
cols2and3 = mda[:,1:]
cols2and3

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
cols2and3 = mda[:,-2:]
cols2and3

array([[2, 3],
       [5, 6],
       [8, 9]])

### Add 2 to the last two elements of the last two rows

In [ ]:
print(mda)
print('-' * 20)
mda[-2:, -2:] += 2
print(mda)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[[ 1  2  3]
 [ 4  7  8]
 [ 7 10 11]]


### Add a row vector to all rows

In [ ]:
mda = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
v = [10, 20, 30]
print(mda + v)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Different Ways to Create Arrays

In [ ]:
ar1 = np.zeros(shape=(6,3), dtype=float)
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ar2 = np.reshape( ar1, (2,-1) )
ar2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
ar3 = ar2.reshape(-1,2)
ar3

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
ar4 = np.linspace(4, 6, 5)
ar4

array([4. , 4.5, 5. , 5.5, 6. ])

### Getting the Number of Rows and Columns in an Array

In [ ]:
mda = np.linspace(1,10,20).reshape(4,5)
print(mda)

[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
 [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]
 [ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
 [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]


In [ ]:
np.size(mda)

20

In [ ]:
np.size(mda, 0)

4

In [ ]:
np.size(mda, 1)

5

In [ ]:
mda.shape

(4, 5)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=dfff8ba7-aef1-4bba-91c9-7743c312b252' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>