Reference: Professor Ami Gates, Dept. Applied Math, Data Science, University of Colorado

This code is actually NOT on her webpage (as of Sept 2023), but just posted as a Python Script file on our Canvas page. 

NN in Python
---


In [1]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
import matplotlib.pyplot as plt

# Data
DATA IS HERE: [https://drive.google.com/file/d/19K2pF77RcxlLNvX9E5hLJP7kBuzYiF1-/view?usp=sharing]

In [2]:
## Create and Train a TINY NN on easy data
filename="HeartRisk_JustNums_Labeled.csv"

## Side Note
If your data is on the web - you can GET it using `keras`

```
csv_file = tf.keras.utils.get_file('filename.csv', 'https://path_to_file_on web.csv')
```


In [3]:
## Notice that I did not hard-code the filename
HeartHealthDF = pd.read_csv(filename)
## Check to see if this worked
print(type(HeartHealthDF))
print(HeartHealthDF.head(15))

<class 'pandas.core.frame.DataFrame'>
     Label  Cholesterol  Weight  Height
0     Risk          251     267      70
1   NoRisk          105     103      62
2   Medium          156     193      72
3   NoRisk          109     100      63
4     Risk          198     210      70
5     Risk          189     189      64
6   NoRisk          121     105      65
7   Medium          134     125      60
8     Risk          250     156      69
9   NoRisk          118     190      71
10    Risk          290     300      62
11  NoRisk          156     119      69
12  NoRisk          145     112      68
13    Risk          178     177      68
14  Medium          175     145      63


## Encoding labels
We have labels - but they are words. 

We will need to encode them as numbers.

In [4]:
from sklearn.preprocessing import LabelEncoder
Label_Encoder = LabelEncoder() ##instantiate your encoder
HeartHealthDF["Label"] = Label_Encoder.fit_transform(HeartHealthDF["Label"])
print(HeartHealthDF)

## Now we have this:
#         Label  Cholesterol  Weight  Height
# 0       2          251     267      70
# 1       1          105     103      62
# 2       0          156     193      72
# 3       1          109     100      63

    Label  Cholesterol  Weight  Height
0       2          251     267      70
1       1          105     103      62
2       0          156     193      72
3       1          109     100      63
4       2          198     210      70
5       2          189     189      64
6       1          121     105      65
7       0          134     125      60
8       2          250     156      69
9       1          118     190      71
10      2          290     300      62
11      1          156     119      69
12      1          145     112      68
13      2          178     177      68
14      0          175     145      63
15      2          221     185      70
16      0          200     185      73
17      2          280     279      70
18      0          156     125      70
19      1          123     120      60
20      0          189     154      69
21      2          268     189      68
22      0          178     140      61
23      2          278     300      68
24      0          166   

**NOTE:** Here, my label is called `Label`. However
that is rarely the case. The label may have been called
"color" (if you are predicting a color) or "salary level", etc. 
In other words, it is important to understand the data
and label that you have.

## Scaling the data
From here - one option is to "scale" our data. 

Let's do that to see how it works. 

**DO NOT SCALE THE LABEL!!** 

Remember - the label is NOT your data. It is the category each data row belongs to ;)

In [5]:
from sklearn.preprocessing import StandardScaler
MyScaler = StandardScaler()  #instantiate the scaler
HeartHealthDF[["Cholesterol",  "Weight",  "Height"]] = MyScaler.fit_transform(HeartHealthDF[["Cholesterol",  "Weight",  "Height"]])
print(HeartHealthDF)

    Label  Cholesterol    Weight    Height
0       2     1.125543  1.740293  0.881091
1       1    -1.324847 -1.133545 -1.150975
2       0    -0.468889  0.443561  1.389108
3       1    -1.257713 -1.186115 -0.896967
4       2     0.236018  0.741459  0.881091
5       2     0.084966  0.373468 -0.642958
6       1    -1.056311 -1.098498 -0.388950
7       0    -0.838125 -0.748030 -1.658991
8       2     1.108759 -0.204805  0.627083
9       1    -1.106661  0.390991  1.135099
10      2     1.780099  2.318565 -1.150975
11      1    -0.468889 -0.853171  0.627083
12      1    -0.653507 -0.975835  0.373075
13      2    -0.099652  0.163187  0.373075
14      0    -0.150002 -0.397562 -0.896967
15      2     0.622038  0.303374  0.881091
16      0     0.269585  0.303374  1.643116
17      2     1.612264  1.950574  0.881091
18      0    -0.468889 -0.748030  0.881091
19      1    -1.022744 -0.835647 -1.658991
20      0     0.084966 -0.239852  0.627083
21      2     1.410862  0.373468  0.373075
22      0  

## Training and Testing dataset

We are using NN here to TRAIN a model. We will then use that model to see if we can predict the right label.

- To TRAIN the model, we need a training dataset.
- To TEST the model's accuracy (etc) we need a DISJOINT Testing dataset.

(Why disjoint?)

In [6]:
from sklearn.model_selection import train_test_split
TRAIN_data, TEST_data = train_test_split(HeartHealthDF, test_size = 0.25)
print(TRAIN_data)
print("\n",TEST_data)

    Label  Cholesterol    Weight    Height
29      1    -0.905259 -1.010881 -0.388950
4       2     0.236018  0.741459  0.881091
12      1    -0.653507 -0.975835  0.373075
14      0    -0.150002 -0.397562 -0.896967
18      0    -0.468889 -0.748030  0.881091
3       1    -1.257713 -1.186115 -0.896967
19      1    -1.022744 -0.835647 -1.658991
2       0    -0.468889  0.443561  1.389108
30      1    -0.821342 -1.098498 -0.642958
28      0    -0.468889 -0.572796 -0.388950
11      1    -0.468889 -0.853171  0.627083
21      2     1.410862  0.373468  0.373075
9       1    -1.106661  0.390991  1.135099
8       2     1.108759 -0.204805  0.627083
0       2     1.125543  1.740293  0.881091
22      0    -0.099652 -0.485179 -1.404983
25      2     1.780099  0.723936  0.881091
20      0     0.084966 -0.239852  0.627083
16      0     0.269585  0.303374  1.643116
13      2    -0.099652  0.163187  0.373075
1       1    -1.324847 -1.133545 -1.150975
26      2     1.796882  0.794029 -1.404983
5       2  

Make sure your training and testing data are balanced.

In other words, that there is a fair representation of all labels. 

***IMPORTANT***

Right now, our testing and training datasets still have the labels ON THEM.

We need to remove the label and save it. 

In [7]:
## Get the label from the training data
Train_Label = TRAIN_data["Label"]  ## Save the label
print(Train_Label)

29    1
4     2
12    1
14    0
18    0
3     1
19    1
2     0
30    1
28    0
11    1
21    2
9     1
8     2
0     2
22    0
25    2
20    0
16    0
13    2
1     1
26    2
5     2
31    1
Name: Label, dtype: int32


In [8]:
## Drop the label from the training set now that you saved it
TRAIN_data = TRAIN_data.drop("Label",  axis=1)
## axis = 1 means drop the column. axis = 0 drops a row
print(TRAIN_data)

    Cholesterol    Weight    Height
29    -0.905259 -1.010881 -0.388950
4      0.236018  0.741459  0.881091
12    -0.653507 -0.975835  0.373075
14    -0.150002 -0.397562 -0.896967
18    -0.468889 -0.748030  0.881091
3     -1.257713 -1.186115 -0.896967
19    -1.022744 -0.835647 -1.658991
2     -0.468889  0.443561  1.389108
30    -0.821342 -1.098498 -0.642958
28    -0.468889 -0.572796 -0.388950
11    -0.468889 -0.853171  0.627083
21     1.410862  0.373468  0.373075
9     -1.106661  0.390991  1.135099
8      1.108759 -0.204805  0.627083
0      1.125543  1.740293  0.881091
22    -0.099652 -0.485179 -1.404983
25     1.780099  0.723936  0.881091
20     0.084966 -0.239852  0.627083
16     0.269585  0.303374  1.643116
13    -0.099652  0.163187  0.373075
1     -1.324847 -1.133545 -1.150975
26     1.796882  0.794029 -1.404983
5      0.084966  0.373468 -0.642958
31    -0.922043 -0.134711  1.389108


OK! Let's do this for the testing data now

In [9]:
## Save the label
Test_Label = TEST_data["Label"]  
print(Test_Label)

23    2
17    2
15    2
6     1
10    2
27    1
7     0
24    0
Name: Label, dtype: int32


In [10]:
## Drop the label from the training set now that you saved it
TEST_data = TEST_data.drop("Label",  axis=1)
## axis = 1 means drop the column. axis = 0 drops a row
print(TEST_data)

    Cholesterol    Weight    Height
23     1.578697  2.318565  0.373075
17     1.612264  1.950574  0.881091
15     0.622038  0.303374  0.881091
6     -1.056311 -1.098498 -0.388950
10     1.780099  2.318565 -1.150975
27    -1.056311 -1.186115  0.119066
7     -0.838125 -0.748030 -1.658991
24    -0.301054 -0.029571 -1.658991


Now - what do we have?

- We have numeric data. 
- We have three dimensional data (3 variables)
- We split our data into a training set and a testing set
- We have the labels for each SEPERATELY!

# Run the NN

In [11]:
from sklearn.neural_network import MLPClassifier

## Instantiate your NN with the parameter values you want

In [12]:
MyNN = MLPClassifier(hidden_layer_sizes=(50,80,50), 
                     max_iter=100,activation = 'relu',solver='adam',random_state=1)

`hidden_layer_sizes` specifies the number of layers (3 there because we have three values in our tuple. )

We are also specifying the number of nodes in the hidden layer. 

## Train the NN Model

In [13]:
MyNN.fit(TRAIN_data, Train_Label)

c:\Users\rokka\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(50, 80, 50), max_iter=100, random_state=1)

Notice that we give the model the data and the label for the data seperately!

## Test the NN Model
Now we can use our test data (WITHOUT the label) to see if our model predicts the label. 

So - the model will predict what it thinks the label should be. 

We have the labels, so we can check to see which labels the model predicted right and wrong. 

We will use a confusion matrix for this

In [14]:
Test_Prediction = MyNN.predict(TEST_data)

In [15]:
print(Test_Prediction)

[2 2 2 1 2 1 1 0]


In [16]:
print(Test_Label)

23    2
17    2
15    2
6     1
10    2
27    1
7     0
24    0
Name: Label, dtype: int32


### Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

#Comparing the predictions against the actual observations 
MyConfusionMatrix = confusion_matrix(Test_Prediction, Test_Label)
print(MyConfusionMatrix)

#Printing the accuracy
print("\n\n The accuracy of the sklearn MLPClassifier is:")
print(accuracy_score(Test_Prediction, Test_Label))

[[1 0 0]
 [1 2 0]
 [0 0 4]]


 The accuracy of the sklearn MLPClassifier is:
0.875
