Module 2 Assignment - Part 2: Multinomial NN with Softmax, Categorical Cross Entropy, and One-Hot Encoding
---

**Instructions:**

This assignment has a two large parts with many sub-parts. Each part will enable you to practice with a neural networks and to practice for Exam 2.

This Assignment will TAKE TIME so use all of the time you have to work on it. Please avoid waiting until the last few days as this will not be enough time. You need weeks - not days :)

Be sure to show all work and (when requested) to code using Python (and no NN/TF/Keras packages). Do not worry, we will use packages in coming modules but first it is best to learn about what is going on inside the model. 

You may use examples and code that I have shared as a reference. Using my code will not be considered cheating although I strongly recommend that you write as much (if not all) of your own code so that you learn the concepts more robustly. 

This is not a team assignment. Please work and code alone. You may discuss concepts, but you cannot share code or work with others. Papers that look too similar with split the grade (first offense) and can suffer less pleasant outcomes for further offenses. Keep it simple and smart - do your own work. 

# 1) Draw NN architecture
In Part 1 above, I created (with an illustration) the NN architecture for you. In this part, you will illustrate (draw) the architecture. 

(a) Your NN architecture (draw this) will expect input vectors of three values (3D data). It will have one hidden layer with two units. It will create four outputs (for four categories), it will use softmax to convert those 4 outputs into a probability distribution, and it will choose the max as the prediction. 

(b) The hidden layer (H1) will be activated with reLU. 

Draw the NN.

Use my slides and what we did during class lecture to help you. Label everything - including the x's, the W1's, the B, the C, the H1 values, the Z2 values, the y^ values (after softmax), and the final output. Again, the class slides have an exact example of this. 

***JK:*** *Check Word Document*

# 2) Write out all the Feed Forward equations

You will have equations for $Z_1$, $H_1$, $Z_2$, $\hat{Y}$.

## JK's answer

### $Z_1$

\begin{align*} 
Z_1 & =  X\cdot W_1 + B

\\
& = 
\begin{bmatrix}
x_{11} & x_{12} & x_{13} \\
\vdots  & \vdots  & \vdots  \\
x_{n1} & x_{n2} & x_{n3} \\
\end{bmatrix}

\begin{bmatrix}
w_{11} & w_{12}  \\
w_{21} & w_{22}  \\
w_{31} & w_{32} 
\end{bmatrix}

+
\begin{bmatrix}
b_1 \\
\vdots \\
b_n
\end{bmatrix}

\\

& = 
\begin{bmatrix}
z_{11} & z_{12}  \\
z_{21} & z_{22}  \\
\vdots & \vdots  \\
z_{n1} & z_{n2} 
\end{bmatrix}
\end{align*}

Where we have:

\begin{align*}
& z_{11} = x_{11}w_{11} + x_{12}w_{21} + x_{13}w_{31} + b_1 & & \\
& z_{12} = x_{11}w_{12} + x_{12}w_{22} + x_{13}w_{32} + b_1 & &\\
\end{align*}

$$\vdots$$

\begin{align*}
z_{n2} = x_{n1}w_{12} + x_{n2}w_{22} + x_{n3}w_{32} + b_n 
\end{align*}

In other words, any $Z$ element can be summarized as,

$$z_{i,k} = \sum_j^3 x_{i,j}w_{j,k} + b_i$$

### $H_1$

We're assuming the first hidden layer uses the reLU activation function.  

reLU function:

\begin{equation*}
f = 
\begin{cases}
x   &\text{if } x > 0 \\
0   &\text{else}
\end{cases}
\end{equation*}

$h$ is the same value as $x$ if it's positive and 0 otherwise. 

The $H1$ matrix is as follows:

\begin{align*}
H_1 & = 
\begin{bmatrix}
f(z_{11}) & f(z_{12}) \\
\vdots    &   \vdots  \\
f(z_{n1}) & f(z_{n2}) \\
\end{bmatrix}

\\

& = 
\begin{bmatrix}
h_{11} & h_{12}  \\
\vdots & \vdots  \\
h_{n1} & h_{n2}  \\
\end{bmatrix}
\end{align*}

The number of columns in $H_1$ is the number of hidden units in the hidden layer.

### $Z_2$

\begin{align*}
Z^{(2)} &= H_1 W^{(2)} + C \\
&= 
\begin{bmatrix}
h_{11} & h_{12} \\
\vdots & \vdots \\
h_{n1} & h_{n2} \\
\end{bmatrix}

\begin{bmatrix}
w_{11}^{(2)} & w_{12}^{(2)} & w_{13}^{(2)} & w_{14}^{(2)}  \\[6pt]
w_{21}^{(2)} & w_{22}^{(2)} & w_{23}^{(2)} & w_{24}^{(2)}  \\[6pt]
\end{bmatrix}

+

\begin{bmatrix}
c_1 \\
\vdots \\
c_n
\end{bmatrix}\\
&= 
\begin{bmatrix}
z_{11}^{(2)} & z_{12}^{(2)} & z_{13}^{(2)} & z_{14}^{(2)} \\
\vdots & \vdots & \vdots & \vdots \\
z_{n1}^{(2)} & z_{n2}^{(2)} & z_{n3}^{(2)} & z_{n4}^{(2)}  
\end{bmatrix}
\end{align*}



Where,

\begin{align*}
& z_{11}^{(2)} = h_{11}w_{11}^{(2)} + h_{12}w_{21}^{(2)} + c_1 & & \\
& z_{12}^{(2)} = h_{11}w_{12}^{(2)} + h_{12}w_{22}^{(2)} + c_1 & &\\
\end{align*}

$$\vdots$$

\begin{align*}
z_{n4}^{(2)} = h_{n1}w_{14}^{(2)} + x_{n2}w_{24}^{(2)} + c_n 
\end{align*}

Or in other words, each $Z^{(2)}$ element can be summarized as,

\begin{align*}
z_{i,l}^{(2)} = \sum_k^2 h_{i,k}w_{k,l}^{(2)} + c_i
\end{align*}

### $\mathbf{\hat{y}}$

And lastly we have the predicted output $\mathbf{\hat{y}}$.

In the case of this architecture, we're expecting 4 outputs. 

And for this assignment, we said we would use the Softmax function, which is defined as follows.

\begin{align*}
\hat{y}_{i,l} = \text{softmax}(z_{i,l}^{(2)}) = \frac{\text{exp}(z_{i,l}^{(2)})}{\displaystyle \sum_l^4 \text{exp}(z_{i,l}^{(2)})}
\end{align*}

Where $\text{exp}(x) = e^x$ (I just used that notation to make the variables easier to see in the fraction.)

The summation from $l=1$ to $l=4$ is due to the fact that we have four possible classes/outcomes for this architecture. (So the formula above is specific to this assignment.)

The softmax function gives the probability distributions of the possible outcomes. So in this case we would have 4 probabilities of the 4 labels from the softmax. (The probabilities are pdfs too, so the probabilities for each instance are non-negative and all sum up to one.)

\begin{align*}
\Rightarrow
\mathbf{\hat{y}} &= 
\begin{bmatrix}
[\hat{y}_{11} & \hat{y}_{12} & \hat{y}_{13} & \hat{y}_{14}] \\
\vdots & \vdots & \vdots & \vdots \\
[\hat{y}_{n1} & \hat{y}_{n2} & \hat{y}_{n3} & \hat{y}_{n4}] \\
\end{bmatrix}\\
&=
\begin{bmatrix}
[\text{softmax}(z_{11}^{(2)}) & \text{softmax}(z_{12}^{(2)}) & \text{softmax}(z_{13}^{(2)}) & \text{softmax}(z_{14}^{(2)})] \\
\vdots & \vdots & \vdots & \vdots \\
[\text{softmax}(z_{n1}^{(2)}) & \text{softmax}(z_{n2}^{(2)}) & \text{softmax}(z_{n3}^{(2)}) & \text{softmax}(z_{n4}^{(2)})]
\end{bmatrix}
\end{align*}

# 3) What are the following derivatives

$\frac{\partial L}{\partial W1} = ?$

$\frac{\partial L}{\partial W2} = ?$

$\frac{\partial L}{\partial B} = ?$

$\frac{\partial L}{\partial C} = ?$ 

(using reLU to activate $Z_1$ to $H_1$, and using Softmax to activate $Z_2$ to $\hat{Y}$)

**Hint:** The slides show a very similar example. The only difference is that the slides use Sigmoid and not reLU. So you will need to update this part. Start by determining the derivative of the reLU.

Use the Categorical Cross Entropy Loss function.

Use One-Hot Encoding for $\mathbf{y}$ (your label)

Show all your work

## JK's answer:

Parameters we want to update via back propagation (and gradient descent):

\begin{aligned}
\begin{array}{ccc}
\hline
\text{Parameter} & \text{Matrix/Vector form} & \text{Shape} \\
\hline 
\\

W^{(1)} & 
\begin{bmatrix}
w_{11} & w_{12}  \\
w_{21} & w_{22}  \\
w_{31} & w_{32} 
\end{bmatrix}
&
[3 \times 2]\\

\\
\hline 
\\

\mathbf{B} &
\begin{bmatrix}
b_1 \\
\vdots \\
b_n
\end{bmatrix}
&
[n \times 1]\\

\\
\hline 
\\

W^{(2)} & 
\begin{bmatrix}
w_{11}^{(2)} & w_{12}^{(2)} & w_{13}^{(2)} & w_{14}^{(2)}  \\[6pt]
w_{21}^{(2)} & w_{22}^{(2)} & w_{23}^{(2)} & w_{24}^{(2)}  \\[6pt]
\end{bmatrix}
&
[2 \times 4]\\

\\
\hline 
\\

\mathbf{C} &
\begin{bmatrix}
c_1 \\
\vdots \\
c_n
\end{bmatrix}
&
[n \times 1]

\end{array}
\end{aligned}

And I believe for gradient descent to work properly, I think the (final matrix/vector form of the) partial derivatives of each parameter needs to match the shape of the original parameter. 


Other relevant formulas:

\begin{aligned}
\begin{array}{c|c|c|c}
\hline
\text{Variable (matrix/vector form)}& \text{Shape} & \text{Vector/Matrix Formula} & \text{Element-wise formula} \\
\hline \\

L_{CCE} & \text{(scalar)} & -log(\mathbf{\hat{y}}) & L = -log(\hat{y_i}) \\
\\
\hline \\

\mathbf{\hat{y}} = 
\begin{bmatrix}
[\hat{y}_{11} & \hat{y}_{12} & \hat{y}_{13} & \hat{y}_{14}] \\
\vdots & \vdots & \vdots & \vdots \\
[\hat{y}_{n1} & \hat{y}_{n2} & \hat{y}_{n3} & \hat{y}_{n4}] \\
\end{bmatrix}
&
[n \times 4]
&
\mathbf{\hat{y}} = \text{softmax}(Z^{(2)})
& \hat{y}_{i,l} =  \frac{\textstyle{\text{exp}}(z_{i,l}^{(2)})}{\displaystyle \sum_l^4 \text{exp}(z_{i,l}^{(2)})}\\
\\
\hline 
\\

Z^{(2)} = 
\begin{bmatrix}
z_{11}^{(2)} & z_{12}^{(2)} & z_{13}^{(2)} & z_{14}^{(2)} \\
\vdots & \vdots & \vdots & \vdots \\
z_{n1}^{(2)} & z_{n2}^{(2)} & z_{n3}^{(2)} & z_{n4}^{(2)}  
\end{bmatrix}
&
[n \times 4]
&
Z^{(2)} = H_1 W^{(2)} + C 
& z_{i,l}^{(2)} = \displaystyle \sum_k^2 h_{i,k}w_{k,l}^{(2)} + c_i \\

\\
\hline
\\

H_1 = 
\begin{bmatrix}
h_{11} & h_{12}  \\
\vdots & \vdots  \\
h_{n1} & h_{n2}  \\
\end{bmatrix}
&
[n \times 2]
&
H_1 = \text{reLU}(Z^{(1)})
&
h_{i,k} = 
\begin{cases}
z_{i,k}^{(1)}   &\text{if } z > 0 \\
0   &\text{else}
\end{cases} \\

\\
\hline
\\

Z^{(1)} =
\begin{bmatrix}
z_{11} & z_{12} & z_{13} & z_{14} \\
z_{21} & z_{22} & z_{23} & z_{24} \\
\vdots & \vdots & \vdots & \vdots \\
z_{n1} & z_{n2} & z_{n3} & z_{n4}
\end{bmatrix}
&
[n \times 4]
& 
Z^{(1)} =  X\cdot W_1 + B
&
z_{i,k}^{(1)} = \displaystyle \sum_j^3 x_{i,j}w_{j,k}^{(1)} + b_i \\

\end{array}
\end{aligned}

Reminder (to self) the following are specific to the architecture of this assignment: 

- $2$ comes from the number of units in the hidden layer
- $3$ comes from the number of inputs/columns in $X$
- $4$ comes from the number of possible labels/outputs in $y$ and $\hat{y}$
- ($n$ in this is supposed to be 6 for the dataset I created)

**Other potentially useful multiplication notation to match with python.**

I will try my best to match the multiplication notation as done in Professor Gates' lecture slides.

Thus, I will use an "o-dot" ($\odot$) to represent matrix multiplcation, (equivalent to `@` in Python) i.e.:

\begin{align*}
A \odot B = 
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}\\
\end{bmatrix}
\odot
\begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22} \\
\end{bmatrix}
=
\begin{bmatrix}
a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\
a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22}
\end{bmatrix}
\end{align*}

And I will use an asterisk ($\ast$) for element-wise ("regular") multiplication, (equivalent to `*` in Python) i.e.:

\begin{align*}
A \ast B = 
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}\\
\end{bmatrix}
\ast
\begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22} \\
\end{bmatrix}
=
\begin{bmatrix}
a_{11}b_{11} & a_{12}b_{12} \\
a_{21}b_{21} & a_{22}b_{22}
\end{bmatrix}
\end{align*}

### $\frac{\partial L}{\partial C}$

\begin{align*}
\frac{\partial L}{\partial C} = \frac{\partial L}{\partial \mathbf{\hat{y}_i}} \cdot \frac{\partial \mathbf{\hat{y}_i}}{\partial Z^{(2)}} \cdot \frac{\partial Z^{(2)}}{\partial C}
\end{align*}

We find the derivative of the softmax in question 5, and in question 6 we remind ourselves from the lectures that when we use a combination of Softmax, Categorical Cross entropy, and One-Hot Encoding, then $\frac{\partial L}{\partial Z^{(2)}} = \hat{y} - y$ (aka "error" in the lecture slides). So I'm going to skip those parts and just find the rest of the relevant partial derivatives. 

\begin{align*}
z_{i,l}^{(2)} &= \sum_k^2 h_{i,k}w_{k,l}^{(2)} + c_i \\
\Rightarrow
\frac{\partial z_{i,l}^{(2)}}{\partial c_i} &= 0 + (1)\\
\Rightarrow
\frac{\partial Z^{(2)}}{\partial C} &= 
\begin{pmatrix}
1 \\
\vdots \\
1
\end{pmatrix}
=
\vec{1}_n
\end{align*}

So in matrix form

\begin{align*}
\frac{\partial L}{\partial C} &= \frac{\partial L}{\partial \mathbf{\hat{y}_i}} \cdot \frac{\partial \mathbf{\hat{y}_i}}{\partial Z^{(2)}} \cdot \frac{\partial Z^{(2)}}{\partial C}\\
&= [\mathbf{\hat{y}} - \mathbf{y}] \ast \vec{1}_n
\end{align*}

### $\frac{\partial L}{\partial W^{(2)}}$

\begin{align*}
\frac{\partial L}{\partial W^{(2)}} &= \underbrace{\frac{\partial L}{\partial \mathbf{\hat{y}_i}} \cdot \frac{\partial \mathbf{\hat{y}_i}}{\partial Z^{(2)}}}_{\frac{\partial L}{\partial Z^{(2)}}} \cdot \frac{\partial Z^{(2)}}{\partial W^{(2)}}\\
&= \frac{\partial L}{\partial Z^{(2)}} \cdot \frac{\partial Z^{(2)}}{\partial W^{(2)}}
\end{align*}

Again, focusing on the other derivatives:

\begin{align*}
z_{i,l}^{(2)} &= \sum_k^2 h_{i,k}w_{k,l}^{(2)} + c_i \\
\Rightarrow
\frac{\partial z_{i,l}^{(2)}}{\partial w_{kl}} &= h_{i,k}(1) + 0\\
\Rightarrow
\frac{\partial Z^{(2)}}{\partial W^{(2)}} &= H_1
\end{align*}

Matrix form:

\begin{align*}
\frac{\partial L}{\partial W^{(2)}} &= \frac{\partial L}{\partial \mathbf{\hat{y}_i}} \cdot \frac{\partial \mathbf{\hat{y}_i}}{\partial Z^{(2)}} \cdot \frac{\partial Z^{(2)}}{\partial W^{(2)}}\\
&= [\mathbf{\hat{y}} - \mathbf{y}] \odot H_1
\end{align*}

### $\frac{\partial L}{\partial B}$

\begin{align*}
\frac{\partial L}{\partial B} &= \underbrace{\frac{\partial L}{\partial \mathbf{\hat{y}}} \cdot \frac{\partial \mathbf{\hat{y}}}{\partial Z^{(2)}}}_{\frac{\partial L}{\partial Z^{(2)}}} \cdot \frac{\partial Z^{(2)}}{\partial H_1} \cdot \frac{\partial H_1}{\partial Z^{(1)}} \cdot \frac{\partial Z^{(1)}}{\partial B} \\
\end{align*}



Starting with $\frac{\partial Z^{(2)}}{\partial H_1}$

\begin{align*}
z_{i,l}^{(2)} &= \displaystyle \sum_k^2 h_{i,k}w_{k,l}^{(2)} + c_i \\
\Rightarrow
\frac{\partial z_{i,l}^{(2)}}{\partial h_{i,k}} &= (1)w_{k,l}^{(2)} + 0 \\
\Rightarrow
\frac{\partial Z^{(2)}}{\partial H_1} &= W^{(2)}
\end{align*}

Then for $\frac{\partial H_1}{\partial Z^{(1)}}$

\begin{align*}
h_{i,k} = \text{reLU}(z_{i,k}^{(1)}) =
\begin{cases}
z_{i,k}^{(1)}   &\text{if } z > 0 \\
0   &\text{else}
\end{cases} 
\end{align*}

We need to start with finding the derivative of the reLU function.

Generically,

\begin{align*}
f(z) =
\begin{cases}
z   &\text{if } z > 0 \\
0   &\text{else}
\end{cases} \\
\Rightarrow
f'(z) =
\begin{cases}
1   &\text{if } z > 0 \\
0   &\text{else}
\end{cases} \\
\end{align*}

So I can summarize this with a matrix, and I can call this matrix, $\Gamma$.

\begin{align*}
\frac{\partial H_1}{\partial Z^{(1)}} = 
\begin{bmatrix}
f'(z_{11}^{(1)}) & f'(z_{12}^{(1)}) & f'(z_{13}^{(1)}) & f'(z_{14}^{(1)}) \\
\vdots & \vdots & \vdots & \vdots \\
f'(z_{n1}^{(1)}) & f'(z_{n2}^{(1)}) & f'(z_{n3}^{(1)}) & f'(z_{n4}^{(1)})
\end{bmatrix} 
= \Gamma
\end{align*}

Then lastly for $\frac{\partial Z^{(1)}}{\partial B}$

\begin{align*}
z_{i,k}^{(1)} &= \displaystyle \sum_j^3 x_{i,j}w_{j,k}^{(1)} + b_i \\
\Rightarrow
\frac{\partial z_{i,k}^{(1)}}{\partial b_i} &= 0 + (1) \\
\Rightarrow
\frac{\partial Z^{(1)}}{\partial B} &=
\begin{bmatrix}
1 \\
\vdots \\
1
\end{bmatrix} 
= \vec{1}_n

\end{align*}

\begin{align*}
\frac{\partial L}{\partial B} &= 
\underbrace{\frac{\partial L}{\partial \mathbf{\hat{y}}} 
\cdot 
\frac{\partial \mathbf{\hat{y}}}{\partial Z^{(2)}}}_{\frac{\partial L}{\partial Z^{(2)}}} 

\cdot 

\underbrace{\frac{\partial Z^{(2)}}{\partial H_1}}_{W^{(2)}}

\cdot 

\underbrace{\frac{\partial H_1}{\partial Z^{(1)}}}_{\Gamma}

\cdot 

\underbrace{\frac{\partial Z^{(1)}}{\partial B}}_{\vec{1}_n} \\
\end{align*}


### $\frac{\partial L}{\partial W^{(1)}}$

\begin{align*}
\frac{\partial L}{\partial W^{(1)}} &= 
\underbrace{\frac{\partial L}{\partial \mathbf{\hat{y}}} 
\cdot 
\frac{\partial \mathbf{\hat{y}}}{\partial Z^{(2)}}}_{\frac{\partial L}{\partial Z^{(2)}}} 

\cdot 

\underbrace{\frac{\partial Z^{(2)}}{\partial H_1}}_{W^{(2)}}

\cdot 

\underbrace{\frac{\partial H_1}{\partial Z^{(1)}}}_{\Gamma}

\cdot 

\frac{\partial Z^{(1)}}{\partial W^{(1)}} \\
\end{align*}

The only derivative I need to find for $\frac{\partial Z^{(1)}}{\partial W^{(1)}}$

\begin{align*}
z_{i,k}^{(1)} &= \displaystyle \sum_j^3 x_{i,j}w_{j,k}^{(1)} + b_i \\
\Rightarrow
\frac{\partial z_{i,k}^{(1)}}{\partial w_{j,k}^{(1)}} &= x_{i,j}(1) + 0 = x_{i,j}\\
\Rightarrow
\frac{\partial Z^{(1)}}{\partial W^{(1)}} &=
X

\end{align*}


Therefore,

\begin{align*}
\frac{\partial L}{\partial W^{(1)}} &= 
\underbrace{\frac{\partial L}{\partial \mathbf{\hat{y}}} 
\cdot 
\frac{\partial \mathbf{\hat{y}}}{\partial Z^{(2)}}}_{\frac{\partial L}{\partial Z^{(2)}}} 

\cdot 

\underbrace{\frac{\partial Z^{(2)}}{\partial H_1}}_{W^{(2)}}

\cdot 

\underbrace{\frac{\partial H_1}{\partial Z^{(1)}}}_{\Gamma}

\cdot 

\underbrace{\frac{\partial Z^{(1)}}{\partial W^{(1)}}}_{X} \\
\end{align*}

# 4) Calculate Softmax results

If your four $Z_2$ values are $1.1, 2.2, 0.2$ and $-1.7$, calculate (by hand and show your work) the four softmax results.

(Yes you can use a calculator or Google for the math - but SHOW THE WORK and steps) If you show just the answer, you will get -50%. 

## JK's answer

Softmax formula:

\begin{align*}
\text{softmax}(z) = \frac{\text{exp}(z)}{\displaystyle \sum_i \text{exp}(z_i)}
\end{align*}


$Z2 = [1.1,2.2,0.2,-1.7]$


### $\text{softmax}(1.1)$

\begin{align*}
\text{softmax}(1.1) &= \frac{e^{1.1}}{e^{1.1} + e^{2.2} + e^{0.2} + e^{-1.7}} \\
& \approx \frac{3.0042}{13.43327} \\
& \approx 0.2236
\end{align*}

### $\text{softmax}(2.2)$

\begin{align*}
\text{softmax}(2.2) &= \frac{e^{2.2}}{e^{1.1} + e^{2.2} + e^{0.2} + e^{-1.7}} \\
& \approx \frac{9.025}{13.43327} \\
& \approx 0.6718
\end{align*}

### $\text{softmax}(0.2)$

\begin{align*}
\text{softmax}(0.2) &= \frac{e^{0.2}}{e^{1.1} + e^{2.2} + e^{0.2} + e^{-1.7}} \\
& \approx \frac{1.2214}{13.43327} \\
& \approx 0.0909
\end{align*}

### $\text{softmax}(-1.7)$

\begin{align*}
\text{softmax}(-1.7) &= \frac{e^{-1.7}}{e^{1.1} + e^{2.2} + e^{0.2} + e^{-1.7}} \\
& \approx \frac{0.18268}{13.43327} \\
& \approx 0.0136
\end{align*}

# 5) Derivative of Softmax

Write out the derivative of the Softmax for the case where $i=j$ and for the case $i$ does not equal $j$. Show all work and steps.

Find and paste in the Jacobian for the derivative of the Softmax and assure that your results (for $i=j$ and $i\neq j$) match the Jacobian values.

## JK's answer:

Reminder:

\begin{align*}
\hat{y}_i = \text{softmax}(z_i) = \frac{\text{exp}(z_i)}{\displaystyle \sum_{j=1}^k \text{exp}(z_j)}
\end{align*}

where $i$ and $j$ go from 1 to $k$, and $k$ is the number of categories.

Thus, we need *two derivatives*, for $\frac{\partial \hat{y}_i}{\partial z_j}$. Cases for when $i=j$ **AND** when $i \neq j$.



### *Case 1:* $i=j$

For simpler notation I'm going to state that all summations are $\displaystyle \sum_{j=1}^k$

\begin{align*}
\frac{\partial \hat{y}_i}{\partial z_j} &= \frac{(e^{z_i})(\sum e^{z_j}) - (e^{z_i})(e^{z_i})}{(\sum e^{z_j})^2}\\[6pt]
&= 
\frac{e^{z_i}}{\sum e^{z_j}} \cdot \left(1 - \frac{e^{z_i}}{\sum e^{z_j}}\right) \\[8pt]

\Rightarrow
\frac{\partial \hat{y}_i}{\partial z_j} &= \hat{y}_i(1 - \hat{y}_i)
\end{align*}

### *Case 2:* $i \neq j$

\begin{align*}
\frac{\partial \hat{y}_i}{\partial z_j} &= \frac{(0)(\sum e^{z_j}) - (e^{z_j})(e^{z_i})}{(\sum e^{z_j})^2}\\[6pt]
&=
\frac{-e^{z_j}e^{z_i}}{(\sum e^{z_j})^2}\\[6pt]

&= 
\frac{e^{z_i}}{\sum e^{z_j}} \cdot \left(- \frac{e^{z_j}}{\sum e^{z_j}}\right) \\[8pt]

\Rightarrow
\frac{\partial \hat{y}_i}{\partial z_j} &= \hat{y}_i(- \hat{y}_j) = -\hat{y}_i\hat{y}_j
\end{align*}

### Jacobian

(For the case in this assignment)

\begin{align*}
J &= 
\begin{bmatrix}
\frac{\partial \hat{y}_1}{\partial z_1} & \frac{\partial \hat{y}_1}{\partial z_2} & \frac{\partial \hat{y}_1}{\partial z_3} & \frac{\partial \hat{y}_1}{\partial z_4} \\[6pt]

\frac{\partial \hat{y}_2}{\partial z_1} & \frac{\partial \hat{y}_2}{\partial z_2} & \frac{\partial \hat{y}_2}{\partial z_3} & \frac{\partial \hat{y}_2}{\partial z_4} \\[6pt]

\frac{\partial \hat{y}_3}{\partial z_1} & \frac{\partial \hat{y}_3}{\partial z_2} & \frac{\partial \hat{y}_3}{\partial z_3} & \frac{\partial \hat{y}_3}{\partial z_4} \\[6pt]

\frac{\partial \hat{y}_4}{\partial z_1} & \frac{\partial \hat{y}_4}{\partial z_2} & \frac{\partial \hat{y}_4}{\partial z_3} & \frac{\partial \hat{y}_4}{\partial z_4} \\[6pt]
\end{bmatrix}\\

&=
\begin{bmatrix}
\hat{y}_1(1-\hat{y}_1) & -\hat{y}_1\hat{y}_2 & -\hat{y}_1\hat{y}_3 & -\hat{y}_1\hat{y}_4 \\[4pt]

-\hat{y}_2\hat{y}_1 & \hat{y}_2(1-\hat{y}_2) & -\hat{y}_2\hat{y}_3 & -\hat{y}_2\hat{y}_4 \\[4pt]

-\hat{y}_3\hat{y}_1 & -\hat{y}_3\hat{y}_2 & \hat{y}_3(1-\hat{y}_3) & -\hat{y}_3\hat{y}_4 \\[4pt]

-\hat{y}_4\hat{y}_1 & -\hat{y}_4\hat{y}_2 & -\hat{y}_4\hat{y}_3 & \hat{y}_4(1-\hat{y}_4) \\[4pt]
\end{bmatrix}\\

\end{align*}

Lecture slide on Jacobians is as follows:
<div>
<img src="j_lecture.PNG" width="800"/>
</div>

The jacobian matrix matches the above calculations.

# 6) Combination

When using the combination of Softmax, Categorical Cross Entropy, and One-Hot Encoding, what is $\frac{\partial L}{\partial Z_2}$ (sometimes written as $\frac{dL}{dz}$ or as "Error" on the slides)?

(Just give the final answer here. You are not required to show work for this part.)

***JK:***

$\frac{\partial L}{\partial Z_2} = \hat{y} - y$

# 7) Code

In **(1)** above, you created a NN architecture for 3D data, a 4-category label (0,1,2,3), one hidden layer (with two units). Write code for this NN without using any NN packages (so by hand)

- Use One-hot Encoding for the label.
- For the Loss Fucntion, use Categorical Cross Entropy.
- For the activation from $Z_1$ to $H_1$, use reLU.
- Run it for 1000 epochs and include the same visualizations as were required in **Part 1 *(5)*** above.
- **YOU** create the dataset and also submit the dataset with your submission.
- Be sure to illustrate some of your results so that the viewer can see what you did.

This code will help (a lot). Here again, I suggest that you try not to use my code :) Try to write this yourself and only use my code as a reference or if you must. ([Prof Gates' Code Example](https://gatesboltonanalytics.com/?page_id=707))

(Note - my code uses Sigmoid - not reLU - so you will need to make some updates anyway).

In [1]:
#%% libraries
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math
from sklearn.preprocessing import LabelEncoder,MinMaxScaler,StandardScaler,OneHotEncoder
from sklearn.metrics import confusion_matrix  
import seaborn as sns
import random

# %%
class OneLayer_MultiOutput():
    def __init__(self,
                 data_filename = "A2_Part2_Data_JasmineKobayashi.csv", 
                 data_normalizer = StandardScaler(),
                 hidden_units= 2,
                 randomize_initial_parameters = False,
                 verbose = True):
        # Read Data
        self.df = pd.read_csv(data_filename)
        
        # create X and y, assuming data has column "LABEL" as column with labels
        ## X matrix
        if data_normalizer is not None:
            self.data_scaler = data_normalizer
            X = self.data_scaler.fit_transform(self.df.drop(columns="LABEL",axis=1))
            print("X was normalized using {}".format(data_normalizer))
        else:
            self.data_scaler = None
            X = np.array(self.df.drop(columns=['LABEL'],axis=1))
            print("X was not normalized")

        self.X = X

        ## y
        self.OHE = OneHotEncoder()
        self.y = self.OHE.fit_transform(self.df[['LABEL']]).toarray()
        

        if verbose:
            print("Shape of X:", self.X.shape)
            print("X matrix: \n", self.X)
            print("Shape of y:", self.y.shape)
            print("y vector: \n", self.y)

        # Shape of W1
        w1_ncol = hidden_units        # Number of W1 cols should be number of hidden units in H1
        w1_nrow = self.X.shape[1]     # Number of W1 rows should be number of X columns (dim of X)
        # Shape of B (column vector)
        b_length = self.X.shape[0]    # length of X rows
        # Shape of W2:
        w2_ncol = self.y.shape[1]                 # Number of W2 cols should be number of outputs (in this case, only one output)
        w2_nrow = hidden_units        # Number of W2 rows should be number of hidden units in H1
        # Shape of C (column vector)
        c_length = self.X.shape[0]    # length of X rows
        
        if randomize_initial_parameters: 
            # TODO: Finish potential code of randomized parameters
            # # bounds of randomized weights
            # bound = 1/np.sqrt(w1_nrow)   # I found online that supposedly this is a standard range for randomized weights
            # rand_w = [np.random.uniform(-bound,bound) for i in range(w1_ncol)]
            # self.W1 = np.array([rand_w]*w1_nrow)

            # self.W2 = np.array([]*w2_nrow)
            # print('All parameters were randomized')
            pass
        else:   # These are the parameters defined by the question 2 in Assignment2
            self.W1 = np.array([[1]*w1_ncol]*w1_nrow) # otherwise, all weights of W1 = 1
            self.B = np.array([[0]]*b_length)         # otherwise, all bias (B) = 0
            self.W2 = np.array([[2]*w2_ncol]*w2_nrow) # otherwise, all weights of W2 = 2
            self.C = np.array([[0]]*c_length)
            print("Parameters built for simple calculation (not randomized)")
        
        if verbose:
            # print("# of X cols (should be # of W1 rows):", self.X.shape[1])
            # print("# of hidden units (should be # of W1 cols):", hidden_units)
            print("W1 has shape:", self.W1.shape)
            print("W1 matrix: \n", self.W1)
            print("Shape of B:", self.B.shape)
            print("B (bias vector for Z1): \n", self.B)
            print("Shape of W2:",self.W2.shape)
            print("W2 matrix: \n", self.W2)
            print("Shape of C :", self.C.shape)
            print("C (bias vector for Z2): \n",self.C)


    def MSE_loss(self,y_hat,y):
        # L = mean((y_hat - y)^2)
        return np.mean((y_hat - y)**2)
        
    def CCE_loss(self,y_hat,y):
        # each row of y and y^ have to be passed individually
        # loss=[]
        # for j in range(y.shape[0]):
        #     loss.append(-y[j]*np.log(y_hat[j]))
        return np.mean(-y * np.log(y_hat))

    def lin_eq(self,X,W,B):
        assert X.shape[1] == W.shape[0], "Linear eq: z = X @ W + B. Shape of X: {}; Shape of W: {}".format(X.shape,W.shape)
        assert B.shape[0] == X.shape[0], "Linear eq: z = X @ W + B. Length of B should match X rows; Length B = {}; Shape of X = {}".format(B.shape[0],X.shape)
        return X @ W + B
    
    def Sigmoid(self,z,
                derivative = False):
        if derivative:
            return self.Sigmoid(z) * (1 - self.Sigmoid(z)) # dS/dz = S(z)(1-S(z))
        # Sigmoid
        return 1/(1 + math.e**(-z)) # S(z) = 1/(1 + e^(-z))
    
    def reLU(self,z,
             derivative = False):
        
        relulist = []
        for row in z:
            if derivative:
                relulist.append([1 if value > 0 else 0 for value in row])
            else:
                relulist.append([max(0.0,value) for value in row])
        return np.array(relulist)
        
    def softmax(self,Z2):
        # SMlist = []
        # for k in range(Z2.shape[0]):
        #     z2_row = Z2[k]
        #     smrow = []
        #     for l in range(Z2.shape[1]):
        #         denominator = np.sum(math.e**(z2_row))
        #         SMz2 = (math.e**z2_row[l])/denominator
        #         smrow.append(SMz2)
        #     SMlist.append(smrow)
        # return np.array(SMlist)
        
        expZ = np.exp(Z2)
        
        SM=expZ/np.sum(expZ, axis=1)[:,None]
        
        return SM 

    def FeedForward(self,
                    activation = "reLU",
                    verbose = True):
        # Create H1
        # Z1 = X @ W1 + B
        self.Z1 = self.lin_eq(self.X,self.W1,self.B)
        if verbose:
            print("Shape of Z1:",self.Z1.shape)
            print("Z1 matrix: \n",self.Z1)
        self.H1 = self.reLU(self.Z1)
        # TODO: Add flexibility with other activation functions
        if verbose: 
            print("Activation function:",activation)
            print("H1 matrix: \n", self.H1)

        # Z2 and y-hat
        # Z2 = H1 @ W2 + C
        self.Z2 = self.lin_eq(self.H1,self.W2,self.C)
        self.y_hat = self.softmax(self.Z2)

        if verbose:
            print("Shape of Z2:", self.Z2.shape)
            print("Z2 matrix: \n", self.Z2)
            print("y_hat:\n",self.y_hat)
        
    
    # Gradient descent----------------------------------------------
    def grad_desc(self,y_hat,y,LR,
                  verbose = True):
        
        # dL/dZ2  = [y^-y]
        self.dL_dZ2 = y_hat - y                                   # shape =  [n x 1]

        self.dH_dZ1 = self.reLU(self.Z1,derivative=True)

        # dL/dC = [dL/dy^][dy^/dZ2][dZ2/C] 
        #       = [y^-y][S(Z2)(1 - S(Z2))][1]
        self.dZ2_dC = np.array([[1]]*self.C.shape[0])           # vector of 1s with same shape of C
        self.dL_dC = self.dL_dZ2 * self.dZ2_dC                            # should match shape of C (n x 1)
        # I don't see a good way to make these matrices match the shape of C, 
        #  so instead I'm going to redefine dL/dC to be a single column vector with the averages 
        #  of each row from the above calculation
        self.dL_dC = np.array([[np.mean(self.dL_dC)]]*self.C.shape[0])

        # dL/dW2 = [dL/dy^][dy^/dZ2][dZ2/W2] 
        #        = [y^-y][S(Z2)(1 - S(Z2))][H1]
        self.dL_dW2 =  self.H1.T @ self.dL_dZ2                         # should match shape of W2 

        # dL/dB = [dL/dy^][dy^/dZ2][dZ2/dH1][dH1/dZ1][dZ1/dB] 
        #       = [dL/dZ2][gamma][W2][1]
        #       = [y^-y] * ([gamma] @ [W2]) * [1] 
        
        self.Gamma = self.reLU(self.Z1,derivative = True)      # should match shape of Z1 (n x 2)
        self.dZ1_dB = np.array([[1]]*self.B.shape[0])           # vector of 1s with same shape of B
        
        self.dL_dB = self.dL_dZ2 * (self.Gamma @ self.W2)  * self.dZ1_dB        # should match shape of B (n x 1)
        # I have the same problem with dL/dB as with dL/dC, so I will do the same thing as did there
        #self.dL_dB = np.array([[np.mean(row)] for row in self.dL_dB])
        self.dL_dB = np.array([[np.mean(self.dL_dB)]]*self.B.shape[0])
        # dL/dW1 = [dL/dy^][dy^/dZ2][dZ2/dH1][dH1/dZ1][dZ1/dW1] 
        #        = [y^-y][S(Z2)(1 - S(Z2))][W2][S(Z1)(1-S(Z1))][X] 
        #        = [X]^T @ [([[y^-y] * [S(Z2)(1 - S(Z2))]] @ [W2]) * [S(Z1)(1-S(Z1))]] 
        #        = [X]^T @ [([E * Phi] * [W2]^T) * Omega]
        self.dL_W1 = self.X.T @ (( (self.dL_dZ2) @ self.W2.T) * self.Gamma)    # should match shape of W1 (3 x 2)

        # Gradient descent
        self.C = self.C - (LR*self.dL_dC)
        self.W2 = self.W2 - (LR*self.dL_dW2)
        self.B = self.B - (LR*self.dL_dB)
        self.W1 = self.W1 - (LR*self.dL_W1)

        if verbose:
            # print("# of X cols (should be # of W1 rows):", self.X.shape[1])
            # print("# of hidden units (should be # of W1 cols):", hidden_units)
            print("Updated W1 has shape:", self.W1.shape)
            print("Updated W1 matrix: \n", self.W1)
            print("Shape of updated B:", self.B.shape)
            print("Updated B (bias vector for Z1): \n", self.B)
            print("Shape of updated W2:",self.W2.shape)
            print("Updated W2 matrix: \n", self.W2)
            print("Shape of updated  C :", self.C.shape)
            print("Updated C (bias vector for Z2): \n",self.C)

    # Visualizations (confusion matrix & Lce plot)==================
    # Confusion matrix-------------------------------------------------------------
    def ConfusionMatrix(self, y_hat,y):
        self.prediction = y_hat
        # self.prediction[y_hat >= .5] = 1
        # self.prediction[y_hat < .5] = 0

        self.labels = y
        
        
        self.cm = confusion_matrix(self.labels, self.prediction)
        print(self.cm)
        plt.figure()
        ax= plt.subplot()
        sns.heatmap(self.cm, annot=True, fmt='g', ax=ax, cmap='Blues')  
        #annot=True to annotate cells, ftm='g' to disable scientific notation

        # labels, title and ticks
        ax.set_xlabel("Predicted labels")
        ax.set_ylabel("True labels")
        ax.set_title("Confusion Matrix")
        ax.xaxis.set_ticklabels(["0", "1"])
        ax.yaxis.set_ticklabels(["0", "1"])
    
    # Plot of Lce vs. Epochs--------------------------------------------------------
    def plot_LCE(self):
        plt.figure()
        plt.plot(np.arange(0,len(self.loss_record)),self.loss_record,'-',label="LR = {}".format(self.LR))
        plt.xlabel("epochs")
        plt.ylabel('Loss')
        plt.title("Loss over epochs")
        plt.legend()

    # Run multiple iterations (with specified epochs, etc.)========================================================
    def run_model(self, 
                  epochs,
                  LR= 1,
                  hidden_units= 4,
                  randomize_parameters = False,
                  activation = "sigmoid", 
                  verbose = True):
        
        # Save LCE values (for plotting)------------------------------------
        self.loss_record = []
        #-------------------------------------------------------------------
        self.LR = LR
        print("Running model for {} epochs...".format(epochs))
        for i in range(epochs):
            print("Epoch",i)
            self.FeedForward(activation= activation,
                             verbose=verbose)
            
            
            self.loss_record.append(self.CCE_loss(y_hat=self.y_hat,
                                                  y=self.y))
            if verbose:
                print("Loss:",self.loss_record[i])

            # Update params with gradient descent---------------------------
            self.grad_desc(y_hat=self.y_hat,
                           y=self.y,
                           LR=self.LR,
                           verbose=verbose)
        print("Finished running all epochs")

        # Visualizations
        self.ConfusionMatrix(y_hat=self.y_hat,y=self.y)
        self.plot_LCE()

    def test_model(self,
                   test_data,
                   verbose = True):
        self.test_df = pd.read_csv(test_data)

        print("X is now input from test data")
        if self.data_scaler is not None:
            self.X = self.data_scaler.transform(self.test_df.drop(columns="LABEL",axis=1))
            print("Test input X was normalized using same normalizer as training ({})".format(self.data_scaler))
        else:
            self.X = self.test_df.drop(columns="LABEL",axis=1)

        self.y = np.array(self.test_df[['LABEL']])

        if verbose:
            print("Shape of X:", self.X.shape)
            print("X matrix: \n", self.X)
            print("Shape of y:", self.y.shape)
            print("y vector: \n", self.y)

        print("Testing model with test data")
        self.FeedForward()
        print("Finished testing model")

        self.ConfusionMatrix(y_hat=self.y_hat,
                             y=self.y)
        

In [2]:
NN = OneLayer_MultiOutput()
NN.FeedForward()
NN.grad_desc(y_hat=NN.y_hat,y=NN.y,LR=1)

X was normalized using StandardScaler()
Shape of X: (16, 3)
X matrix: 
 [[ 0.92819243 -1.27475541  1.61048338]
 [ 0.30643674 -0.63663915 -0.75580778]
 [ 0.46631677  0.56869158 -0.2328705 ]
 [-1.87859043  1.25407572 -0.88218428]
 [ 0.87489909 -1.20385361  1.48410687]
 [ 0.27090784 -0.61300521 -0.55099068]
 [ 0.50184567  0.68686126  0.06781843]
 [ 0.96372133 -1.22748754  1.66713492]
 [ 0.43078788  0.49778977 -0.17186116]
 [-1.6121237   1.39587933 -0.98677174]
 [-1.48777256  1.23044178 -0.97369831]
 [ 0.94595688 -1.34565722  1.78479581]
 [-1.73647484  1.20680785 -1.03470766]
 [ 0.32420118 -0.68390702 -0.46383447]
 [ 0.44855232  0.7104952  -0.0236956 ]
 [ 0.25314339 -0.56573734 -0.53791725]]
Shape of y: (16, 4)
y vector: 
 [[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
Parameters built for simple ca

In [3]:
epochs =10
for i in range(epochs):
    NN.FeedForward()
    NN.grad_desc(y_hat=NN.y_hat,y=NN.y,LR=1)

Shape of Z1: (16, 2)
Z1 matrix: 
 [[ 1.2639204   1.2639204 ]
 [-1.08601019 -1.08601019]
 [ 0.80213785  0.80213785]
 [-1.50669899 -1.50669899]
 [ 1.15515236  1.15515236]
 [-0.89308805 -0.89308805]
 [ 1.25652536  1.25652536]
 [ 1.40336871  1.40336871]
 [ 0.75671649  0.75671649]
 [-1.2030161  -1.2030161 ]
 [-1.23102908 -1.23102908]
 [ 1.38509547  1.38509547]
 [-1.56437465 -1.56437465]
 [-0.8235403  -0.8235403 ]
 [ 1.13535192  1.13535192]
 [-0.85051119 -0.85051119]]
Activation function: reLU
H1 matrix: 
 [[1.2639204  1.2639204 ]
 [0.         0.        ]
 [0.80213785 0.80213785]
 [0.         0.        ]
 [1.15515236 1.15515236]
 [0.         0.        ]
 [1.25652536 1.25652536]
 [1.40336871 1.40336871]
 [0.75671649 0.75671649]
 [0.         0.        ]
 [0.         0.        ]
 [1.38509547 1.38509547]
 [0.         0.        ]
 [0.         0.        ]
 [1.13535192 1.13535192]
 [0.         0.        ]]
Shape of Z2: (16, 4)
Z2 matrix: 
 [[ 9.25484097 12.43184471 -0.73197963 -0.73197963]
 [ 0.   

C:\Users\rokka\AppData\Local\Temp\ipykernel_3576\1768068881.py:133: RuntimeWarning: overflow encountered in exp
  expZ = np.exp(Z2)
C:\Users\rokka\AppData\Local\Temp\ipykernel_3576\1768068881.py:135: RuntimeWarning: invalid value encountered in divide
  SM=expZ/np.sum(expZ, axis=1)[:,None]


**JK:** For some reason I'm getting `NaN`s when certain amount of epochs for this code.

But I'm afraid this is far as I'll have to go. I admittedly did not give myself adequate time to finish this assignment. And I have gotten stuck for several hours on this particular code, and am feeling too sick to try to work through it anymore myself. 

(I will try my best to get something working by the exam, but as far as this assignment is concerned this is as much as I'm going to have to submit).